### ISSUE TITLE
VRM Import Issue: Nonexistent Function 'get_surface_material'

### ISSUE THREAD

**Issue by GunGryphon** [ExpiredPopsicle/SnekStudio#16]
I'm encountering an invalid call error when loading my VRM.
When I go to load my VRM... 
![image](https://github.com/user-attachments/assets/7bf8a148-ae0d-4f37-a7ac-2c036e76b021)
... it halts with this error: 
Invalid call. Nonexistent function 'get_surface_material' in base 'ImporterMeshInstance3D (importer_mesh_attributes.gd)'.

![image](https://github.com/user-attachments/assets/74fee51b-5d52-466b-8b8c-2f25b387eda6)
The only noteworthy item on the errors tab is this entry:
E 0:03:21:0616   vrm_utils.gd:66 @ adjust_mesh_zforward(): Condition "p_blend_shapes.size() != blend_shapes.size()" is true.
  <C++ Source>   scene/resources/3d/importer_mesh.cpp:160 @ add_surface()
  <Stack Trace>  vrm_utils.gd:66 @ adjust_mesh_zforward()
                 vrm_utils.gd:95 @ rotate_scene_180()
                 vrm_extension.gd:971 @ _import_post()
                 ModelController.gd:71 @ load_vrm()
                 Main.gd:543 @ load_vrm()
                 UI_Root.gd:46 @ _on_vrm_load_file_dialog_file_selected()

I'm not the most well versed on setting up VRMs so it's entirely possible it's a bit scuffed, but I have used this same file in VSeeFace before.
![image](https://github.com/user-attachments/assets/f8d7ae58-8c37-4083-a6f1-c281665cec16)

Model Notes:
The model has a handful of separate meshes and materials. There's a separate material slot for each eye as they are controlled using UV offset drivers. 
![image](https://github.com/user-attachments/assets/c9f414bd-b664-47e0-a4f3-53a5e768a9d2)

**Comment by ExpiredPopsicle** [comment]
This miiiiiiiight be a problem with the VRM import addon we're using from V-Sekai ( https://github.com/V-Sekai/godot-vrm/ ). I'll mention it to the devs and see if we're on our own for fixing this, or if another report should be made over there.

Thanks for the report, and I'm sorry you haven't been able to get the model loaded yet.

**Comment by ExpiredPopsicle** [comment]
So it turns out that there were issues with both the VRM addon, and a lack of implementation for those UV offsets in SnekStudio itself.

PR is up for the VRM addon here: https://github.com/V-Sekai/godot-vrm/pull/109
SnekStudio fix to go with it is incoming in a moment.

**Comment by ExpiredPopsicle** [comment]
SnekStudio fix is in df487be44019022dd54f3816fcc57c0e7b5cc34e .

I'm not going to mark this closed until the PR gets approved on the V-Sekai Godot VRM addon side, and I get a chance to update the git submodule. But if you're feeling adventurous, and comfortable with git, you can try integrating the commit from the branch from the PR and it should work now.

**Comment by ExpiredPopsicle** [comment]
I just went ahead and added the stuff from the Godot-VRM addon that we needed in this commit: 09c134f

You should be good to go, now.
