### ISSUE TITLE
Work around Windows long filename path issues

### ISSUE THREAD

**Issue by ExpiredPopsicle** [ExpiredPopsicle/SnekStudio#18]

**Comment by digital-mint-creature** [comment]
FYI, if you're running into this issue, note that you *might* be able to work around it before a fix is released (depending on the length of your Windows username) by enabling [`Use Custom User Dir`](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-application-config-use-custom-user-dir) in `Project Settings > Application > Config` (this is Godot's project settings, not the in-game settings; also, you have to enable "Advanced Settings" in the top-right to see it). Once you've done that, set [`Custom User Dir Name`](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-application-config-custom-user-dir-name) (should be right next to the previous setting) to something short.

This will change the data directory from `%AppData%\Roaming\Godot\app_userdata\SnekStudio` to `%AppData%\Roaming\{custom_name}` - best-case scenario, you can save ~28 characters, which was enough to get it working for me (13-character Windows username).

**Comment by digital-mint-creature** [comment]
For documentation purposes: the errors that this led to for me looked like this:
```
E 0:00:07:0747   KiriTARReader.gd:389 @ unpack_file(): Can't write file: user://_python_dist/cpython-3.12.5+20240814-x86_64-pc-windows-msvc-shared-install_only_stripped/python/Lib/site-packages/pkg_resources/_vendor/importlib_resources/__pycache____init__.cpython-312.pyc
  <C++ Source>   core/variant/variant_utility.cpp:1092 @ push_error()
  <Stack Trace>  KiriTARReader.gd:389 @ unpack_file()
                 KiriPythonBuildWrangler.gd:152 @ unpack_python()
                 KiriPythonWrapperInstance.gd:63 @ setup_python()
                 MediaPipeController.gd:68 @ _ready()
                 Main.gd:460 @ deserialize_settings()
                 Main.gd:537 @ load_settings()
                 Main.gd:92 @ _ready()
```

Which then led to a `Cannot call method 'store_buffer' on a null value` error that paused execution. Resuming execution after this error broke many parts of the application (amusingly, this did *not* include rendering but it *did* include collision, so loading a model would cause it to immediately fall through the floor).

**Comment by ExpiredPopsicle** [comment]
I *think* we've mitigated this during the changes for the Python build juggling (ending in 42cdf9c ). Let me know if it's still causing issues.
