### ISSUE TITLE
Set up Discord/Matrix stuff

### ISSUE THREAD

**Issue by ExpiredPopsicle** [ExpiredPopsicle/SnekStudio#19]
Set up moderation for Matrix side and make the matrix room public.

Add a link to the Discord to the website.

Make it clear the rooms are bridged.

**Comment by ExpiredPopsicle** [comment]
Almost have the Discord setup working, but there's an issue with the Discord bot in that it's sending stuff to the wrong channel.

**Comment by ExpiredPopsicle** [comment]
Aaaaaand we're done. Invite link is on the website.

**Comment by alyssais** [comment]
Matrix still says coming soon on the website — was something missed?

**Comment by ExpiredPopsicle** [comment]
That's still coming, eventually, but I'm having some issues with the bridge.

**Comment by ExpiredPopsicle** [comment]
@alyssais , in case you were still waiting for this, the Matrix space is now up here: [#snekstudio:matrix.expiredpopsicle.com](https://matrix.to/#/#snekstudio:matrix.expiredpopsicle.com)

(Be advised, these rooms are currently bridged to the Discord server.)
