### ISSUE TITLE
Camera Hardware Does Not Appear to be Getting Used

### ISSUE THREAD

**Issue by GunGryphon** [ExpiredPopsicle/SnekStudio#28]
While running Snek Studio, my main selected camera (Anker C200) sits idle and nothing appears to be tracking.
 
I pulled a fresh clone of the repo and followed the readme as written. I've been able to successfully get my VRM to import thanks to the previous VRM fix. 
![image](https://github.com/user-attachments/assets/905e7fad-2a47-4ece-843b-896c6fb30669)

The camera has an LED that powers on every time the device is in use and it has remained off while trying to use it in Snek Studio. I have been able to use it in the past with VSeeFace, Nyan Studio, and the Expression bridge service (none of which are running currently).

I can also manually open a camera app which turns the camera on (and it's LED) and uses it fine while Snek Studio is running in editor.
![image](https://github.com/user-attachments/assets/90191445-d100-4f97-928d-6cbb2a545e84)

**Comment by ExpiredPopsicle** [comment]
Removed the DSHOW-only restriction for camera devices in ac72238 . I'm going to mark this as fixed, but if it still doesn't work, let me know here and we can re-open it.
