### ISSUE TITLE
Fresh clone and re-import leaves modified files

### ISSUE THREAD

**Issue by copygirl** [ExpiredPopsicle/SnekStudio#30]
I freshly cloned the repository and before doing anything else I've noticed some files have already been modified after opening the project in Godot:

- `godot.project` has a new `[dotnet]` section. I'm sure that's because I opened the project in the Mono/C# version of Godot, which I use for my own project, and doesn't actually have anything to do with the project. Maybe it's worth mentioning it in the Godot issue tracker, as it's not really relevant until any C# code is being used.
- `thumbsup.png.import` is created for the screenshot that's likely only supposed to be used for the readme. My suggestion is to move it to another folder (personally I'd use `docs/`?) and put an empty `.gdignore` file in that folder to have Godot ignore it.
- `addons/godot-vrm/node_constraint/icons/` has two SVG files that are modified after the re-import process:

```diff
@@ -3,15 +3,15 @@
 importer="texture"
 type="CompressedTexture2D"
 uid="uid://c44wulwtgxh3k"
-path="res://.godot/imported/bone_node_constraint.svg-02a074f2e4ecc183996b19e0e710b229.ctex"
+path="res://.godot/imported/bone_node_constraint.svg-6e66d84dae2114aaa38ad7d77bdfdf88.ctex"
 metadata={
 "vram_texture": false
 }
 
 [deps]
 
-source_file="res://addons/vrm/node_constraint/icons/bone_node_constraint.svg"
-dest_files=["res://.godot/imported/bone_node_constraint.svg-02a074f2e4ecc183996b19e0e710b229.ctex"]
+source_file="res://addons/godot-vrm/node_constraint/icons/bone_node_constraint.svg"
+dest_files=["res://.godot/imported/bone_node_constraint.svg-6e66d84dae2114aaa38ad7d77bdfdf88.ctex"]
 
 [params]
 
```
Notably, the path changed form `vrm` to `godot-vrm` so I wonder if things update because of that.

**Comment by ExpiredPopsicle** [comment]
Fixed the thumbsup.png issue in 31753d91272770d08c4b0ac98899c1ba74638499 .
Fixed the .import issue in 31753d91272770d08c4b0ac98899c1ba74638499 .
Won't be changing the godot.project file because the project is not expected to be run with the Mono/C# version of Godot.
