### ISSUE TITLE
Model immediately falls through the floor

### ISSUE THREAD

**Issue by liclac** [ExpiredPopsicle/SnekStudio#6]
If I open SnekStudio, the default untextured snek head shows up onscreen, before immediately falling through the plane below in a few frames. I can find it again by translating downwards (Shift+Right Mouse drag).

![image](https://github.com/user-attachments/assets/b261d620-7ca5-429a-8633-2ebb21ff38f3)
![image](https://github.com/user-attachments/assets/8757bbc2-01ce-4dbb-977f-fa2c7beb8228)

The same thing happens if I load my own VRM. Though I suppose I could use this by just moving the camera below the floor tbh.

![image](https://github.com/user-attachments/assets/f42b9d70-d2cd-47cf-8e72-c485196fe9eb)
![image](https://github.com/user-attachments/assets/00bf826f-c3dd-46ed-88f0-4230ee247c03)

**Comment by ExpiredPopsicle** [comment]
This has been an issue for a while. Thanks for recording it.

Once tracking starts (once the camera is setup and tracking data is received) the head should reset to a normal height.

Let me know if this is not the case.

**Comment by ExpiredPopsicle** [comment]
Should be fixed in 70519621b9c8b6aac06767ec717b97626201d0da .
