### ISSUE TITLE
Support both portable and system-wide installations of SnekStudio

### ISSUE THREAD

**Issue by copygirl** [ExpiredPopsicle/SnekStudio#71]
With #64 being closed with my concern unaddressed, I worry the my [AUR package](https://aur.archlinux.org/packages/snekstudio-bin) is going to have to be abandoned. If SnekStudio only supports settings placed next to the executable, then a system-wide installation can't exist, because it can't write to that directory. And even then, it could not support multiple users.

I would be willing to look offer a solution with the help of a PR, but first I'd like to know which approach to take, as there are some open questions. Also, if SnekStudio is simply just not meant to be installed system-wide, I'd like to know so I don't put effort into something that is unwanted.

One of my suggestions is to simply ask the user where they would like to store their data on first launch. This would then create a settings file that could be detected on subsequent launches. It would also still allow for a "portable" version that simple ships with a pre-created settings file to skip that step. It would check the executable dir before the userdata dir, allowing for one to have both a portable version and a system wide install, if they wish.

There's still the problem with, how would a system installed version of SnekStudio know that it's not supposed to ask the user? (You can't write to the installation directory, after all.) I suggest making the program look for a file in the installation directory.

With that file, my other suggestion would be to make multiple paths configurable in a Linux-friendly way. So for example, for my Arch package, I would configure them as such:
- Settings go in `$XDG_CONFIG_HOME/SnekStudio` (`.config`)
- Mods can go in `$XDG_CONFIG_HOME/SnekStudio/mods` and `/usr/lib/SnekStudio/mods` in addition to the ones shipped with SnekStudio itself. This allows for more mods to be installed system-wide as packages, as well as manually, per-user.
- The rest can stay in the default Godot directory (`.local/share`), though there is the possibility of separating (Python) cache and log files out as well.

Let me know what you think.

**Comment by ExpiredPopsicle** [comment]
Added SNEKSTUDIO_CONFIG_PATH, SNEKSTUDIO_CACHE_PATH, and SNEKSTUDIO_MODS_PATHS (last one used like the PATH variable with ':' delimeters) environment variable overrides in [11caacf](https://github.com/ExpiredPopsicle/SnekStudio/commit/11caacf097c90ba57a3b70f80414f5954c167938) .

**Comment by ExpiredPopsicle** [comment]
You can use those to override all the locations you mentioned for your packaging purposes.

**Comment by copygirl** [comment]
Thank you! :green_heart:
